//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperstarGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperstarGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Superstar.ShowGroup&quot; = &quot;Show Group&quot;
        ///&quot;Superstar.Generate&quot; = &quot;Generate&quot;
        ///&quot;Superstar.LoadGroup&quot; = &quot;Load&quot;
        ///&quot;Superstar.LoadGroup.Title&quot; = &quot;Select file to load group from&quot;
        ///&quot;Superstar.LoadGroup.InvalidFile&quot; = &quot;Invalid File&quot;
        ///&quot;Superstar.Generate.InvalidSize&quot; = &quot;Size must be greater than 0&quot;
        ///&quot;Superstar.Generate.InvalidValue&quot; = &quot;Input not in correct format&quot;
        ///&quot;Superstar.Generate.GroupSize&quot; = &quot;Group Size&quot;
        ///&quot;Superstar.Generate.GroupSize.Tooltip&quot; = &quot;Amount of members to generate&quot;
        ///
        ///&quot;Superstar.Confirm&quot; = &quot;CONFIRM&quot;
        ///&quot;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Superstar.ShowGroup&quot; = &quot;Gruppe anzeigen&quot;
        ///&quot;Superstar.Generate&quot; = &quot;Generieren&quot;
        ///&quot;Superstar.LoadGroup&quot; = &quot;Laden&quot;
        ///&quot;Superstar.LoadGroup.Title&quot; = &quot;Datei von der Gruppe geladen werden soll auswählen&quot;
        ///&quot;Superstar.LoadGroup.InvalidFile&quot; = &quot;Invalide Datei&quot;
        ///&quot;Superstar.Generate.InvalidSize&quot; = &quot;Wert muss größer 0 sein&quot;
        ///&quot;Superstar.Generate.InvalidValue&quot; = &quot;Eingabe nicht in korrektem Format&quot;
        ///&quot;Superstar.Generate.GroupSize&quot; = &quot;Gruppen Größe&quot;
        ///&quot;Superstar.Generate.GroupSize.Tooltip&quot; = &quot;Anzahl an zu generierenden Mitglie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savanah Moody
        ///Nigel Kelley
        ///Evie Huff
        ///Caitlyn Trujillo
        ///Carolina Beltran
        ///Leila Barr
        ///Joyce Lucas
        ///Eliezer Christian
        ///Isis Duke
        ///Alvin Pena
        ///Kailyn Carpenter
        ///Nyasia Poole
        ///Taylor Rangel
        ///Hailie Petersen
        ///Ashlee Mahoney
        ///Daniel Houston
        ///Lillian Gill
        ///Zechariah Hill
        ///Christina Kaufman
        ///Will Lane
        ///Scott Frost
        ///Aylin Cantrell
        ///Kael Morse
        ///Ernest Black
        ///Ruben Kirk
        ///Nadia Gay
        ///William Carlson
        ///Meredith Shepherd
        ///Shyann Simon
        ///Dallas Russell
        ///Sammy Stephens
        ///Gloria Durham
        ///Keyon Swanson
        ///Angie Yoder
        ///Kamari Gib [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
    }
}
