//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiderstandGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiderstandGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Widerstand.ResistanceUnit&quot; = &quot;{0} Ω&quot;
        ///
        ///&quot;Widerstand.Resistance&quot; = &quot;Resistance&quot;
        ///&quot;Widerstand.Target&quot; = &quot;Target&quot;
        ///&quot;Widerstand.Difference&quot; = &quot;Difference&quot;
        ///
        ///
        ///&quot;Widerstand.Resistors.Title&quot; = &quot;&quot;
        ///&quot;Widerstand.Resistors.Resistors&quot; = &quot;Resistors&quot;
        ///
        ///&quot;Widerstand.Resistors.Generator.Minimum&quot; = &quot;Minimum&quot;
        ///&quot;Widerstand.Resistors.Generator.Minimum.Tooltip&quot; = &quot;Minimum Resistance&quot;
        ///&quot;Widerstand.Resistors.Generator.Maximum&quot; = &quot;Maximum&quot;
        ///&quot;Widerstand.Resistors.Generator.Maximum.Tooltip&quot; = &quot;Maximum Resistance&quot;
        ///&quot;Widerstand.Resi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Widerstand.ResistanceUnit&quot; = &quot;{0} Ω&quot;
        ///
        ///&quot;Widerstand.Resistance&quot; = &quot;Widerstand&quot;
        ///&quot;Widerstand.Target&quot; = &quot;Ziel&quot;
        ///&quot;Widerstand.Difference&quot; = &quot;Differenz&quot;
        ///
        ///
        ///&quot;Widerstand.Resistors.Title&quot; = &quot;&quot;
        ///&quot;Widerstand.Resistors.Resistors&quot; = &quot;Widerstände&quot;
        ///
        ///&quot;Widerstand.Resistors.Generator.Minimum&quot; = &quot;Minimum&quot;
        ///&quot;Widerstand.Resistors.Generator.Minimum.Tooltip&quot; = &quot;Minimum Widerstand&quot;
        ///&quot;Widerstand.Resistors.Generator.Maximum&quot; = &quot;Maximum&quot;
        ///&quot;Widerstand.Resistors.Generator.Maximum.Tooltip&quot; = &quot;Maximum Widerstand&quot;
        ///&quot;Widerstand.Resis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
    }
}
