//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VollDanebenGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VollDanebenGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;VollDaneben.LuckyNumbers&quot; = &quot;Lucky\nNumbers&quot;
        ///&quot;VollDaneben.Choices&quot; = &quot;Choices&quot;
        ///
        ///&quot;VollDaneben.Revenue&quot; = &quot;Revenue&quot;
        ///&quot;VollDaneben.Expenditure&quot; = &quot;Expenditure&quot;
        ///&quot;VollDaneben.Total&quot; = &quot;Total&quot;
        ///
        ///&quot;VollDaneben.Currency&quot; = &quot;{0} $&quot;
        ///
        ///
        ///&quot;VollDaneben.Choices.Title&quot; = &quot;&quot;
        ///&quot;VollDaneben.Choices.Choices&quot; = &quot;Choices&quot;
        ///&quot;VollDaneben.Choices.SelectFile&quot; = &quot;Select file&quot;
        ///
        ///
        ///&quot;VollDaneben.Settings.Title&quot; = &quot;Settings&quot;
        ///
        ///&quot;VollDaneben.Settings.Solver&quot; = &quot;Solver&quot;
        ///
        ///&quot;VollDaneben.Settings.Solver.Start&quot; = &quot;Start&quot;
        ///&quot;VollDaneben [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;VollDaneben.LuckyNumbers&quot; = &quot;Glücks-\nzahlen&quot;
        ///&quot;VollDaneben.Choices&quot; = &quot;Wahlen&quot;
        ///
        ///&quot;VollDaneben.Revenue&quot; = &quot;Einnahmen&quot;
        ///&quot;VollDaneben.Expenditure&quot; = &quot;Ausgaben&quot;
        ///&quot;VollDaneben.Total&quot; = &quot;Gesamt&quot;
        ///
        ///&quot;VollDaneben.Currency&quot; = &quot;{0} €&quot;
        ///
        ///
        ///&quot;VollDaneben.Choices.Title&quot; = &quot;&quot;
        ///&quot;VollDaneben.Choices.Choices&quot; = &quot;Wahlen&quot;
        ///&quot;VollDaneben.Choices.SelectFile&quot; = &quot;Datei auswählen&quot;
        ///
        ///
        ///&quot;VollDaneben.Settings.Title&quot; = &quot;Einstellungen&quot;
        ///
        ///&quot;VollDaneben.Settings.Solver&quot; = &quot;Löser&quot;
        ///
        ///&quot;VollDaneben.Settings.Solver.Start&quot; = &quot;Start&quot;
        ///&quot;Voll [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
    }
}
