//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwistGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwistGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Twist.TwistButton&quot; = &quot;Twist&quot;
        ///&quot;Twist.DetwistButton&quot; = &quot;Detwist&quot;
        ///&quot;Twist.Settings&quot; = &quot;Select Language&quot;
        ///
        ///&quot;Twist.FileSelector.Long&quot; = &quot;Select file to (de)twist&quot;
        ///&quot;Twist.FileSelector.Invalid&quot; = &quot;Invalid file&quot;
        ///
        ///&quot;Twist.Finished.Title&quot; = &quot;Finished&quot;
        ///&quot;Twist.Finished.SaveResults&quot; = &quot;Save Results to&quot;
        ///
        ///&quot;Twist.Langcook.Open&quot; = &quot;Select .langcook or files to convert to one&quot;
        ///&quot;Twist.Langcook.Save&quot; = &quot;Save .langcook to&quot;.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Twist.TwistButton&quot; = &quot;Twisten&quot;
        ///&quot;Twist.DetwistButton&quot; = &quot;Enttwisten&quot;
        ///&quot;Twist.Settings&quot; = &quot;Sprache auswählen&quot;
        ///
        ///&quot;Twist.FileSelector.Long&quot; = &quot;Dateien zum (ent)twisten auswählen&quot;
        ///&quot;Twist.FileSelector.Invalid&quot; = &quot;Invalide Datei&quot;
        ///
        ///&quot;Twist.Finished.Title&quot; = &quot;Fertig&quot;
        ///&quot;Twist.Finished.SaveResults&quot; = &quot;Ergebnisse speichern nach&quot;
        ///
        ///&quot;Twist.Langcook.Open&quot; = &quot;.langcook Datei oder Dateien zum erstellen einer auswählen&quot;
        ///&quot;Twist.Langcook.Save&quot; = &quot;.langcook speichern nach&quot;.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
    }
}
